const $ = (q)=>document.querySelector(q); const $$=(q)=>document.querySelectorAll(q);
function navActive(){const p=location.pathname; $$('.nav a').forEach(a=>a.classList.toggle('active', a.getAttribute('href')===p || (p==='/'&&a.getAttribute('href')==='/')))}
function menu(){const b=$('#menuBtn'), s=$('.sidebar'); if(b&&s){b.onclick=()=>s.classList.toggle('open'); document.addEventListener('click',e=>{if(innerWidth<900&&!s.contains(e.target)&&e.target!==b)s.classList.remove('open')})}}
function money(n){return '$'+Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function initBase(){navActive();menu(); const y=$('#year'); if(y)y.textContent=new Date().getFullYear()}
function initTerminal(){ if(!$('#chart')) return; let symbol='BTCUSDT', equity=100000,balance=100000,floating=0,last=0,series,chart,ws;
 chart=LightweightCharts.createChart($('#chart'),{layout:{background:{color:'#071019'},textColor:'#cfe0ef'},grid:{vertLines:{color:'rgba(255,255,255,.05)'},horzLines:{color:'rgba(255,255,255,.05)'}},rightPriceScale:{borderColor:'rgba(255,255,255,.12)'},timeScale:{borderColor:'rgba(255,255,255,.12)',timeVisible:true,secondsVisible:false},crosshair:{mode:1}});
 series=chart.addCandlestickSeries({upColor:'#26d07c',downColor:'#ff5571',borderUpColor:'#26d07c',borderDownColor:'#ff5571',wickUpColor:'#26d07c',wickDownColor:'#ff5571'});
 new ResizeObserver(()=>chart.applyOptions({width:$('#chart').clientWidth,height:$('#chart').clientHeight})).observe($('#chart'));
 function connect(){ if(ws) ws.close(); const proto=location.protocol==='https:'?'wss':'ws'; ws=new WebSocket(`${proto}://${location.host}/ws/market`); ws.onopen=()=>{ws.send(JSON.stringify({symbol})); $('#conn').textContent='Live feed connected'}; ws.onmessage=(ev)=>{const m=JSON.parse(ev.data); if(m.type==='history'){series.setData(m.candles); chart.timeScale().fitContent()} if(m.type==='candle'){series.update(m.candle); last=m.price; $('#livePrice').textContent=money(last); $('#spread').textContent=(Math.random()*1.8+.2).toFixed(1)+' pts'; floating+=(Math.random()-.5)*18; equity=balance+floating; $('#equity').textContent=money(equity); $('#floating').textContent=money(floating); $('#loss').textContent=Math.max(0,((100000-equity)/1000)*100).toFixed(1)+'%'; $('#targetBar').style.width=Math.min(100,Math.max(0,((equity-100000)/10000)*100))+'%'; }}; ws.onclose=()=>{$('#conn').textContent='Reconnecting...'; setTimeout(connect,1200)}} connect();
 $$('.sym').forEach(b=>b.onclick=()=>{symbol=b.dataset.symbol; $$('.sym').forEach(x=>x.classList.remove('active')); b.classList.add('active'); $('#symbolTitle').textContent=symbol; connect()});
 $('#tradeBtn')?.addEventListener('click',()=>{const row=document.createElement('tr'); const side=Math.random()>.5?'BUY':'SELL'; row.innerHTML=`<td>${new Date().toLocaleTimeString()}</td><td>${symbol}</td><td class="${side==='BUY'?'green':'red'}">${side}</td><td>${money(last||0)}</td><td>Open</td>`; $('#positionsBody').prepend(row)});
 $('#resetBtn')?.addEventListener('click',()=>{equity=balance=100000;floating=0;$('#positionsBody').innerHTML='';$('#equity').textContent=money(equity);$('#floating').textContent=money(0);$('#loss').textContent='0.0%';$('#targetBar').style.width='0%'})}

document.addEventListener('DOMContentLoaded',()=>{initBase();initTerminal()});
