const BRAND='Dropz Universal Propfirm Trading';
const symbols={BTCUSDT:67250,ETHUSDT:3520,XAUUSD:2335,EURUSD:1.0845,NAS100:19780};
let active=localStorage.getItem('dropzSymbol')||'BTCUSDT', candles=[], positions=[], equity=100000, balance=100000, dayLoss=0, target=10000, running=true;
const $=s=>document.querySelector(s); const fmt=n=> active==='EURUSD'? Number(n).toFixed(5):'$'+Number(n).toLocaleString(undefined,{maximumFractionDigits:2});
function nav(){document.querySelectorAll('.nav a,.drawer a').forEach(a=>{let href=a.getAttribute('href'); if(location.pathname.endsWith(href)|| (location.pathname==='/'&&href==='index.html')) a.classList.add('active')});}
function drawer(){const b=$('.mobile-menu'),d=$('.drawer'); if(b&&d)b.onclick=()=>d.classList.toggle('open');}
function seed(){let p=symbols[active], now=Math.floor(Date.now()/60000)*60-80*60; candles=[]; for(let i=0;i<80;i++){let o=p; let drift=(Math.random()-.47)*(p*.002); let c=Math.max(.0001,o+drift); let h=Math.max(o,c)+Math.random()*p*.0012; let l=Math.min(o,c)-Math.random()*p*.0012; candles.push({time:now+i*60,open:o,high:h,low:l,close:c}); p=c;} symbols[active]=p;}
function step(){let last=candles[candles.length-1]; if(!last)return; let p=last.close; let o=p; let trend=Math.sin(Date.now()/17000)*(p*.0009); let c=Math.max(.0001,p+(Math.random()-.5)*(p*.003)+trend); let h=Math.max(o,c)+Math.random()*p*.0015; let l=Math.min(o,c)-Math.random()*p*.0015; candles.push({time:last.time+60,open:o,high:h,low:l,close:c}); candles=candles.slice(-100); symbols[active]=c; renderAll();}
function drawChart(){let canvas=$('#chart'); if(!canvas)return; let r=canvas.getBoundingClientRect(); let dpr=devicePixelRatio||1; canvas.width=r.width*dpr; canvas.height=r.height*dpr; let ctx=canvas.getContext('2d'); ctx.scale(dpr,dpr); let w=r.width,h=r.height; ctx.clearRect(0,0,w,h); ctx.fillStyle='#07101d';ctx.fillRect(0,0,w,h); let pad=34, data=candles.slice(-64); let max=Math.max(...data.map(c=>c.high)), min=Math.min(...data.map(c=>c.low)); let y=v=>pad+(max-v)/(max-min)*(h-pad*2); let cw=(w-pad*2)/data.length; ctx.strokeStyle='#13243c';ctx.lineWidth=1;ctx.font='11px Inter';ctx.fillStyle='#6f829d'; for(let i=0;i<6;i++){let yy=pad+i*(h-pad*2)/5;ctx.beginPath();ctx.moveTo(pad,yy);ctx.lineTo(w-pad,yy);ctx.stroke();let val=max-(max-min)*i/5;ctx.fillText(active==='EURUSD'?val.toFixed(5):val.toFixed(2),w-pad+4,yy+4)} data.forEach((c,i)=>{let x=pad+i*cw+cw/2, green=c.close>=c.open; ctx.strokeStyle=green?'#17d48b':'#ff4d6d';ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y(c.high));ctx.lineTo(x,y(c.low));ctx.stroke();let top=y(Math.max(c.open,c.close)), bot=y(Math.min(c.open,c.close));ctx.fillRect(x-cw*.32,top,Math.max(3,cw*.64),Math.max(2,bot-top));}); ctx.fillStyle='#eef4ff';ctx.font='800 14px Inter';ctx.fillText(`${active} • Simulated 1M`,pad,22);}
function renderMetrics(){let e=$('#equity'),b=$('#balance'),f=$('#floating'),dl=$('#dayLoss'),tp=$('#targetProgress'); let floating=positions.reduce((s,p)=>s+p.pnl,0); equity=balance+floating; if(e)e.textContent='$'+equity.toLocaleString(undefined,{maximumFractionDigits:2}); if(b)b.textContent='$'+balance.toLocaleString(undefined,{maximumFractionDigits:2}); if(f){f.textContent=(floating>=0?'+':'')+'$'+floating.toFixed(2);f.className=floating>=0?'up':'down'} if(dl)dl.textContent=Math.min(100,Math.abs(dayLoss/1000*100)).toFixed(1)+'%'; let prog=Math.max(0,Math.min(100,((equity-100000)/target)*100)); if(tp)tp.textContent=prog.toFixed(1)+'%'; let bar=$('.bar'); if(bar)bar.style.width=prog+'%';}
function renderWatch(){let w=$('#watchlist'); if(!w)return; w.innerHTML=''; Object.keys(symbols).forEach(s=>{let ch=(Math.random()-.45)*1.8; let btn=document.createElement('button');btn.innerHTML=`<span>${s}</span><span class='${ch>=0?'up':'down'}'>${ch>=0?'+':''}${ch.toFixed(2)}%</span>`;btn.onclick=()=>{active=s;localStorage.setItem('dropzSymbol',s);seed();renderAll();};w.appendChild(btn);});}
function renderPositions(){let body=$('#positionsBody'); if(!body)return; body.innerHTML=positions.length?positions.map(p=>`<tr><td>${p.symbol}</td><td>${p.side}</td><td>${p.size}</td><td>${fmt(p.entry)}</td><td class='${p.pnl>=0?'up':'down'}'>${p.pnl>=0?'+':''}$${p.pnl.toFixed(2)}</td></tr>`).join(''):`<tr><td colspan='5'>No open positions. Use Simulate Trade on the terminal.</td></tr>`;}
function renderAll(){document.querySelectorAll('[data-symbol]').forEach(e=>e.textContent=active); drawChart(); renderMetrics(); renderWatch(); renderPositions();}
function buttons(){document.querySelectorAll('[data-symbol-btn]').forEach(b=>{b.onclick=()=>{active=b.dataset.symbolBtn;localStorage.setItem('dropzSymbol',active);seed();renderAll();document.querySelectorAll('[data-symbol-btn]').forEach(x=>x.classList.toggle('active',x.dataset.symbolBtn===active));}; b.classList.toggle('active',b.dataset.symbolBtn===active)}); let sim=$('#simulateTrade'); if(sim)sim.onclick=()=>{let price=symbols[active], side=Math.random()>.5?'BUY':'SELL'; positions.unshift({symbol:active,side,size:(Math.random()*1.5+.1).toFixed(2),entry:price,pnl:(Math.random()*420-120)}); positions=positions.slice(0,8); renderAll();}; let close=$('#closeAll'); if(close)close.onclick=()=>{let pnl=positions.reduce((s,p)=>s+p.pnl,0); balance+=pnl; if(pnl<0)dayLoss+=pnl; positions=[]; renderAll();}; let reset=$('#reset'); if(reset)reset.onclick=()=>{balance=100000;equity=100000;dayLoss=0;positions=[];seed();renderAll();};}
document.addEventListener('DOMContentLoaded',()=>{nav();drawer();seed();buttons();renderAll();setInterval(()=>{positions.forEach(p=>p.pnl+=(Math.random()-.48)*26); if(running)step();},1200);addEventListener('resize',drawChart);});
