services:
  - type: web
    name: dropz-universal-propfirm-trading
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATA_PROVIDER
        value: binance
